// <auto-generated />
using CadastrarMedico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastrarMedico.Migrations
{
    [DbContext(typeof(CadastrarMedicoContext))]
    [Migration("20210418183154_primeirobdmedico")]
    partial class primeirobdmedico
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CadastrarMedico.Models.Medicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AtendeSUS");

                    b.Property<bool>("Cooperador");

                    b.Property<string>("Especialidade");

                    b.Property<bool>("FoiVisitado");

                    b.Property<string>("Nome");

                    b.Property<int>("Telefone");

                    b.Property<bool>("TemKit");

                    b.Property<string>("UnidadeAtendimento");

                    b.Property<string>("observacoes");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });
#pragma warning restore 612, 618
        }
    }
}
